os: linux
language: python

python:
  - "3.8"
  - "3.9"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run --rm app sh -c "python manage.py test && flake8"

after_success:
  - coveralls



# install: "pip install -r requirements.txt"
# before_script:
#   - cp .env.example .env
#   - python manage.py migrate
