os: linux
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

# env:
#   - DJANGO_VERSION=3.2.3
#   - DJANGO_SETTINGS_MODULE='developer_journal.settings'

install:
  - pip install -r requirements.txt
  # - pip install codecov
  # - pip install pytest-cov
  # - pip install .
script:
  - python manage.py test

# after_success:
#   - codecov

# deploy:
#   provider: pypi
#   user: __token__
#   password: $TEST_PYPI_TOKEN
#   distributions: "sdist bdist_wheel"
#   skip_existing: true
#   on:
#     branch: staging