version: "3.9"

services:
  # db:
  #   image: postgres
  #   # volumes:
  #   #   - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  web:
    restart: always
    env_file: .env
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - ./developer_journal:/developer_journal
      - .:/code
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    environment:
      DEBUG: 'true'

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
